export const UPDATE_POST_LIST_PENDING = "post/UPDATE_POST_LIST_PENDING";
export const UPDATE_POST_LIST_FULFILLED = "post/UPDATE_POST_LIST_FULFILLED";
export const UPDATE_POST_LIST_REJECTED = "post/UPDATE_POST_LIST_REJECTED";
export const CREATE_POST = "post/CREATE_POST";